-- =============================================================================
-- School Examination Marks and Report Card Management System
-- Database Schema - PostgreSQL 15+ Compatible
-- =============================================================================
-- Database:    school_report_card
-- Target:      PostgreSQL 15 / 16 / 17 / 18
-- Encoding:    UTF8
-- Schema:      public
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. CLEANUP & EXTENSIONS (Clean Migration State)
-- -----------------------------------------------------------------------------
-- Drop tables in reverse dependency order if re-running on an existing database
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS generated_reports CASCADE;
DROP TABLE IF EXISTS school_settings CASCADE;
DROP TABLE IF EXISTS report_assessment_selections CASCADE;
DROP TABLE IF EXISTS report_configurations CASCADE;
DROP TABLE IF EXISTS calculation_settings CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TABLE IF EXISTS teacher_assignments CASCADE;
DROP TABLE IF EXISTS assessment_applicability CASCADE;
DROP TABLE IF EXISTS assessments CASCADE;
DROP TABLE IF EXISTS assessment_types CASCADE;
DROP TABLE IF EXISTS student_subject_allocations CASCADE;
DROP TABLE IF EXISTS student_academic_records CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS class_subjects CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS sections CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS terms CASCADE;
DROP TABLE IF EXISTS academic_years CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Drop trigger function if exists
DROP FUNCTION IF EXISTS trigger_set_updated_at CASCADE;

-- Drop ENUM types if exist
DROP TYPE IF EXISTS report_type_enum CASCADE;
DROP TYPE IF EXISTS calculation_method_enum CASCADE;
DROP TYPE IF EXISTS mark_result_status_enum CASCADE;
DROP TYPE IF EXISTS teacher_assignment_type_enum CASCADE;
DROP TYPE IF EXISTS assessment_status_enum CASCADE;
DROP TYPE IF EXISTS student_placement_status_enum CASCADE;
DROP TYPE IF EXISTS subject_category_enum CASCADE;
DROP TYPE IF EXISTS academic_year_status_enum CASCADE;

-- -----------------------------------------------------------------------------
-- 1. ENUM TYPE DEFINITIONS
-- -----------------------------------------------------------------------------
CREATE TYPE academic_year_status_enum AS ENUM ('open', 'closed');
CREATE TYPE subject_category_enum AS ENUM ('main', 'elective');
CREATE TYPE student_placement_status_enum AS ENUM ('active', 'internal_transfer', 'withdrawn', 'transferred_out');
CREATE TYPE assessment_status_enum AS ENUM ('active', 'inactive');
CREATE TYPE teacher_assignment_type_enum AS ENUM ('subject_teacher', 'class_teacher');
CREATE TYPE mark_result_status_enum AS ENUM ('blank', 'numeric', 'absent');
CREATE TYPE calculation_method_enum AS ENUM ('average_percentage', 'combined_marks');
CREATE TYPE report_type_enum AS ENUM ('exam', 'term', 'final');

-- -----------------------------------------------------------------------------
-- 2. REUSABLE TRIGGER FUNCTION FOR updated_at
-- Emulates MySQL's ON UPDATE CURRENT_TIMESTAMP behavior faithfully.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- TABLE 1: roles
-- System roles for access control
-- =============================================================================
CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)     NOT NULL,
    description     VARCHAR(255)    NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_roles_name ON roles (LOWER(name));

CREATE TRIGGER trg_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 2: users
-- Application user accounts; deactivated users are never deleted
-- =============================================================================
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT          NOT NULL,
    username        VARCHAR(100)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    display_name    VARCHAR(150)    NOT NULL,
    email           VARCHAR(255)    NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ     NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX uk_users_username ON users (LOWER(username));
CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_users_is_active ON users (is_active);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 3: academic_years
-- Academic year lifecycle: open → closed
-- Only one year should normally be current (enforced by application logic)
-- =============================================================================
CREATE TABLE academic_years (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(20)                 NOT NULL,
    start_date      DATE                        NULL,
    end_date        DATE                        NULL,
    status          academic_year_status_enum   NOT NULL DEFAULT 'open',
    is_current      BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ                 NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_academic_years_name ON academic_years (LOWER(name));

CREATE TRIGGER trg_academic_years_updated_at
    BEFORE UPDATE ON academic_years
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 4: terms
-- Dynamically configurable terms within an academic year
-- =============================================================================
CREATE TABLE terms (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id    BIGINT          NOT NULL,
    name                VARCHAR(100)    NOT NULL,
    sequence_no         INTEGER         NOT NULL,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_terms_year_seq
        UNIQUE (academic_year_id, sequence_no),
    CONSTRAINT uk_terms_year_name
        UNIQUE (academic_year_id, name),

    CONSTRAINT fk_terms_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TRIGGER trg_terms_updated_at
    BEFORE UPDATE ON terms
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 5: classes
-- Master class definitions (e.g. 1, 2, 8, 9, 10)
-- =============================================================================
CREATE TABLE classes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_classes_name ON classes (LOWER(name));

CREATE TRIGGER trg_classes_updated_at
    BEFORE UPDATE ON classes
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 6: sections
-- Academic-year-specific sections within a class
-- =============================================================================
CREATE TABLE sections (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id    BIGINT          NOT NULL,
    class_id            BIGINT          NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_sections_year_class_name
        UNIQUE (academic_year_id, class_id, name),

    CONSTRAINT fk_sections_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_sections_class
        FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_sections_academic_year_id ON sections (academic_year_id);
CREATE INDEX idx_sections_class_id ON sections (class_id);

CREATE TRIGGER trg_sections_updated_at
    BEFORE UPDATE ON sections
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 7: subjects
-- Master subject catalogue
-- =============================================================================
CREATE TABLE subjects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150)            NOT NULL,
    code            VARCHAR(50)             NULL,
    category        subject_category_enum   NOT NULL DEFAULT 'main',
    is_active       BOOLEAN                 NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_subjects_name ON subjects (LOWER(name));

CREATE TRIGGER trg_subjects_updated_at
    BEFORE UPDATE ON subjects
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 8: class_subjects
-- Academic-year configuration linking classes/sections to subjects.
-- subject_name_snapshot preserves the historical subject name for reports.
--
-- Functional uniqueness with COALESCE(section_id, 0) prevents duplicate
-- configurations for both section-specific and class-wide configurations.
-- =============================================================================
CREATE TABLE class_subjects (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id        BIGINT          NOT NULL,
    class_id                BIGINT          NOT NULL,
    section_id              BIGINT          NULL,
    subject_id              BIGINT          NOT NULL,
    subject_name_snapshot   VARCHAR(150)    NOT NULL,
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_class_subjects_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_class_subjects_class
        FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_class_subjects_section
        FOREIGN KEY (section_id) REFERENCES sections (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_class_subjects_subject
        FOREIGN KEY (subject_id) REFERENCES subjects (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Functional UNIQUE index for nullable section_id
CREATE UNIQUE INDEX uk_class_subjects_config
    ON class_subjects (academic_year_id, class_id, (COALESCE(section_id, 0)), subject_id);

CREATE INDEX idx_class_subjects_academic_year_id ON class_subjects (academic_year_id);
CREATE INDEX idx_class_subjects_class_id ON class_subjects (class_id);
CREATE INDEX idx_class_subjects_section_id ON class_subjects (section_id);
CREATE INDEX idx_class_subjects_subject_id ON class_subjects (subject_id);

CREATE TRIGGER trg_class_subjects_updated_at
    BEFORE UPDATE ON class_subjects
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 9: students
-- Student master records. Names are NOT unique.
-- Re-import creates new student records; no automatic matching.
-- =============================================================================
CREATE TABLE students (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name    VARCHAR(200)    NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_students_student_name ON students (student_name);

CREATE TRIGGER trg_students_updated_at
    BEFORE UPDATE ON students
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 10: student_academic_records
-- Historical student academic placements.
-- Transfers create new rows; old placements are never destructively updated.
-- =============================================================================
CREATE TABLE student_academic_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          BIGINT                          NOT NULL,
    academic_year_id    BIGINT                          NOT NULL,
    class_id            BIGINT                          NOT NULL,
    section_id          BIGINT                          NOT NULL,
    roll_number         INTEGER                         NOT NULL,
    status              student_placement_status_enum   NOT NULL DEFAULT 'active',
    effective_from      DATE                            NOT NULL,
    effective_to        DATE                            NULL,
    created_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_sar_year_class_section_roll
        UNIQUE (academic_year_id, class_id, section_id, roll_number),

    CONSTRAINT fk_sar_student
        FOREIGN KEY (student_id) REFERENCES students (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_sar_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_sar_class
        FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_sar_section
        FOREIGN KEY (section_id) REFERENCES sections (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_sar_student_id ON student_academic_records (student_id);
CREATE INDEX idx_sar_academic_year_id ON student_academic_records (academic_year_id);
CREATE INDEX idx_sar_class_id ON student_academic_records (class_id);
CREATE INDEX idx_sar_section_id ON student_academic_records (section_id);

CREATE TRIGGER trg_student_academic_records_updated_at
    BEFORE UPDATE ON student_academic_records
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 11: student_subject_allocations
-- Which subjects apply to each student.
-- =============================================================================
CREATE TABLE student_subject_allocations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_academic_record_id  BIGINT                  NOT NULL,
    class_subject_id            BIGINT                  NOT NULL,
    allocation_type             subject_category_enum   NOT NULL DEFAULT 'main',
    effective_from              DATE                    NOT NULL,
    effective_to                DATE                    NULL,
    is_active                   BOOLEAN                 NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_ssa_record_subject
        UNIQUE (student_academic_record_id, class_subject_id),

    CONSTRAINT fk_ssa_academic_record
        FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ssa_class_subject
        FOREIGN KEY (class_subject_id) REFERENCES class_subjects (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_ssa_student_academic_record_id ON student_subject_allocations (student_academic_record_id);
CREATE INDEX idx_ssa_class_subject_id ON student_subject_allocations (class_subject_id);

CREATE TRIGGER trg_student_subject_allocations_updated_at
    BEFORE UPDATE ON student_subject_allocations
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 12: assessment_types
-- Master assessment type definitions (e.g. Class Test, Term Exam)
-- =============================================================================
CREATE TABLE assessment_types (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_assessment_types_name ON assessment_types (LOWER(name));

CREATE TRIGGER trg_assessment_types_updated_at
    BEFORE UPDATE ON assessment_types
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 13: assessments
-- Individual assessment instances. term_id is nullable (e.g. Final Exam).
-- =============================================================================
CREATE TABLE assessments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id    BIGINT                  NOT NULL,
    term_id             BIGINT                  NULL,
    assessment_type_id  BIGINT                  NOT NULL,
    name                VARCHAR(150)            NOT NULL,
    assessment_date     DATE                    NULL,
    status              assessment_status_enum  NOT NULL DEFAULT 'active',
    created_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_assessments_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_assessments_term
        FOREIGN KEY (term_id) REFERENCES terms (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_assessments_type
        FOREIGN KEY (assessment_type_id) REFERENCES assessment_types (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_assessments_academic_year_id ON assessments (academic_year_id);
CREATE INDEX idx_assessments_term_id ON assessments (term_id);
CREATE INDEX idx_assessments_assessment_type_id ON assessments (assessment_type_id);

CREATE TRIGGER trg_assessments_updated_at
    BEFORE UPDATE ON assessments
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 14: assessment_applicability
-- Links assessments to class/subjects with per-subject maximum marks.
-- =============================================================================
CREATE TABLE assessment_applicability (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id       BIGINT          NOT NULL,
    class_subject_id    BIGINT          NOT NULL,
    maximum_marks       NUMERIC(6,2)    NOT NULL,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_aa_assessment_class_subject
        UNIQUE (assessment_id, class_subject_id),

    CONSTRAINT fk_aa_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_aa_class_subject
        FOREIGN KEY (class_subject_id) REFERENCES class_subjects (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,

    -- maximum_marks must be > 0
    CONSTRAINT chk_aa_max_marks_positive
        CHECK (maximum_marks > 0)
);

CREATE INDEX idx_aa_assessment_id ON assessment_applicability (assessment_id);
CREATE INDEX idx_aa_class_subject_id ON assessment_applicability (class_subject_id);

CREATE TRIGGER trg_assessment_applicability_updated_at
    BEFORE UPDATE ON assessment_applicability
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 15: teacher_assignments
-- Maps teacher users to their academic scope.
-- Class teacher: subject_id IS NULL.
-- Subject teacher: subject_id IS NOT NULL.
-- =============================================================================
CREATE TABLE teacher_assignments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT                          NOT NULL,
    academic_year_id    BIGINT                          NOT NULL,
    class_id            BIGINT                          NOT NULL,
    section_id          BIGINT                          NOT NULL,
    subject_id          BIGINT                          NULL,
    assignment_type     teacher_assignment_type_enum    NOT NULL,
    effective_from      DATE                            NOT NULL,
    effective_to        DATE                            NULL,
    is_active           BOOLEAN                         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ta_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ta_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ta_class
        FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ta_section
        FOREIGN KEY (section_id) REFERENCES sections (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ta_subject
        FOREIGN KEY (subject_id) REFERENCES subjects (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,

    -- Scope consistency check
    CONSTRAINT chk_ta_assignment_subject_consistency
        CHECK (
            (assignment_type = 'class_teacher' AND subject_id IS NULL)
            OR
            (assignment_type = 'subject_teacher' AND subject_id IS NOT NULL)
        )
);

CREATE INDEX idx_ta_user_id ON teacher_assignments (user_id);
CREATE INDEX idx_ta_academic_year_id ON teacher_assignments (academic_year_id);
CREATE INDEX idx_ta_class_id ON teacher_assignments (class_id);
CREATE INDEX idx_ta_section_id ON teacher_assignments (section_id);
CREATE INDEX idx_ta_subject_id ON teacher_assignments (subject_id);

CREATE TRIGGER trg_teacher_assignments_updated_at
    BEFORE UPDATE ON teacher_assignments
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 16: marks
-- Individual student marks per assessment applicability.
-- Three result states: blank, numeric, absent.
-- =============================================================================
CREATE TABLE marks (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_academic_record_id      BIGINT                  NOT NULL,
    student_subject_allocation_id   BIGINT                  NOT NULL,
    assessment_applicability_id     BIGINT                  NOT NULL,
    mark_value                      NUMERIC(6,2)            NULL,
    result_status                   mark_result_status_enum NOT NULL DEFAULT 'blank',
    entered_by_user_id              BIGINT                  NULL,
    updated_by_user_id              BIGINT                  NULL,
    created_at                      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_marks_allocation_applicability
        UNIQUE (student_subject_allocation_id, assessment_applicability_id),

    CONSTRAINT fk_marks_academic_record
        FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_marks_subject_allocation
        FOREIGN KEY (student_subject_allocation_id) REFERENCES student_subject_allocations (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_marks_assessment_applicability
        FOREIGN KEY (assessment_applicability_id) REFERENCES assessment_applicability (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_marks_entered_by
        FOREIGN KEY (entered_by_user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_marks_updated_by
        FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,

    -- Result status consistency check
    CONSTRAINT chk_marks_result_consistency
        CHECK (
            (result_status = 'numeric' AND mark_value IS NOT NULL AND mark_value >= 0)
            OR
            (result_status = 'blank' AND mark_value IS NULL)
            OR
            (result_status = 'absent' AND mark_value IS NULL)
        )
);

CREATE INDEX idx_marks_student_academic_record_id ON marks (student_academic_record_id);
CREATE INDEX idx_marks_student_subject_allocation_id ON marks (student_subject_allocation_id);
CREATE INDEX idx_marks_assessment_applicability_id ON marks (assessment_applicability_id);
CREATE INDEX idx_marks_entered_by_user_id ON marks (entered_by_user_id);
CREATE INDEX idx_marks_updated_by_user_id ON marks (updated_by_user_id);

CREATE TRIGGER trg_marks_updated_at
    BEFORE UPDATE ON marks
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 17: attendance
-- Term-level attendance per student placement.
-- =============================================================================
CREATE TABLE attendance (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_academic_record_id  BIGINT          NOT NULL,
    term_id                     BIGINT          NOT NULL,
    days_attended               INTEGER         NOT NULL DEFAULT 0,
    total_working_days          INTEGER         NOT NULL DEFAULT 0,
    entered_by_user_id          BIGINT          NOT NULL,
    updated_by_user_id          BIGINT          NOT NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_attendance_record_term
        UNIQUE (student_academic_record_id, term_id),

    CONSTRAINT fk_attendance_academic_record
        FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_attendance_term
        FOREIGN KEY (term_id) REFERENCES terms (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_attendance_entered_by
        FOREIGN KEY (entered_by_user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_attendance_updated_by
        FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,

    -- Attendance bounds
    CONSTRAINT chk_attendance_days_not_negative
        CHECK (days_attended >= 0),
    CONSTRAINT chk_attendance_total_not_negative
        CHECK (total_working_days >= 0),
    CONSTRAINT chk_attendance_days_within_total
        CHECK (days_attended <= total_working_days)
);

CREATE INDEX idx_attendance_student_academic_record_id ON attendance (student_academic_record_id);
CREATE INDEX idx_attendance_term_id ON attendance (term_id);

CREATE TRIGGER trg_attendance_updated_at
    BEFORE UPDATE ON attendance
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 18: calculation_settings
-- One calculation method per class per academic year.
-- =============================================================================
CREATE TABLE calculation_settings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id    BIGINT                  NOT NULL,
    class_id            BIGINT                  NOT NULL,
    calculation_method  calculation_method_enum NOT NULL,
    created_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_cs_year_class
        UNIQUE (academic_year_id, class_id),

    CONSTRAINT fk_cs_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_cs_class
        FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TRIGGER trg_calculation_settings_updated_at
    BEFORE UPDATE ON calculation_settings
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 19: report_configurations
-- Flexible report configuration; configuration_data JSONB for extensibility.
-- =============================================================================
CREATE TABLE report_configurations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id    BIGINT              NULL,
    name                VARCHAR(150)        NOT NULL,
    report_type         report_type_enum    NOT NULL,
    configuration_data  JSONB               NULL,
    is_active           BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rc_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_rc_academic_year_id ON report_configurations (academic_year_id);
CREATE INDEX idx_rc_report_type ON report_configurations (report_type);

CREATE TRIGGER trg_report_configurations_updated_at
    BEFORE UPDATE ON report_configurations
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 20: report_assessment_selections
-- Controls which assessments appear in a report and their display order.
-- =============================================================================
CREATE TABLE report_assessment_selections (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_configuration_id     BIGINT          NOT NULL,
    assessment_id               BIGINT          NOT NULL,
    display_order               INTEGER         NOT NULL,
    is_displayed                BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_ras_config_assessment
        UNIQUE (report_configuration_id, assessment_id),

    CONSTRAINT fk_ras_report_config
        FOREIGN KEY (report_configuration_id) REFERENCES report_configurations (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ras_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_ras_report_configuration_id ON report_assessment_selections (report_configuration_id);
CREATE INDEX idx_ras_assessment_id ON report_assessment_selections (assessment_id);
CREATE INDEX idx_ras_config_display_order ON report_assessment_selections (report_configuration_id, display_order);

CREATE TRIGGER trg_report_assessment_selections_updated_at
    BEFORE UPDATE ON report_assessment_selections
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 21: school_settings
-- Singleton school configuration.
-- =============================================================================
CREATE TABLE school_settings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_name         VARCHAR(200)    NOT NULL,
    school_logo_path    VARCHAR(500)    NULL,
    pass_mark           NUMERIC(6,2)    NOT NULL DEFAULT 0.00,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- pass_mark must be >= 0
    CONSTRAINT chk_ss_pass_mark_non_negative
        CHECK (pass_mark >= 0)
);

CREATE TRIGGER trg_school_settings_updated_at
    BEFORE UPDATE ON school_settings
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================================
-- TABLE 22: generated_reports
-- Historical PDF report records. PDFs are NEVER overwritten.
-- Revision identity uniqueness prevents duplicate revision numbers for the same context.
-- =============================================================================
CREATE TABLE generated_reports (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_academic_record_id  BIGINT              NOT NULL,
    report_type                 report_type_enum    NOT NULL,
    term_id                     BIGINT              NULL,
    assessment_id               BIGINT              NULL,
    revision_number             INTEGER             NOT NULL DEFAULT 1,
    file_path                   VARCHAR(500)        NOT NULL,
    generated_by_user_id        BIGINT              NOT NULL,
    generated_at                TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_gr_academic_record
        FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_gr_term
        FOREIGN KEY (term_id) REFERENCES terms (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_gr_assessment
        FOREIGN KEY (assessment_id) REFERENCES assessments (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_gr_generated_by
        FOREIGN KEY (generated_by_user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Functional UNIQUE index for revision identity with nullable term_id & assessment_id
CREATE UNIQUE INDEX uk_gr_revision_identity
    ON generated_reports (
        student_academic_record_id,
        report_type,
        (COALESCE(term_id, 0)),
        (COALESCE(assessment_id, 0)),
        revision_number
    );

CREATE INDEX idx_gr_student_academic_record_id ON generated_reports (student_academic_record_id);
CREATE INDEX idx_gr_term_id ON generated_reports (term_id);
CREATE INDEX idx_gr_assessment_id ON generated_reports (assessment_id);
CREATE INDEX idx_gr_generated_by_user_id ON generated_reports (generated_by_user_id);

-- =============================================================================
-- TABLE 23: audit_logs
-- Immutable activity history. Must NEVER be deleted through the application.
-- =============================================================================
CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NULL,
    action          VARCHAR(100)    NOT NULL,
    entity_type     VARCHAR(100)    NOT NULL,
    entity_id       BIGINT          NULL,
    before_data     JSONB           NULL,
    after_data      JSONB           NULL,
    description     TEXT            NULL,
    ip_address      VARCHAR(45)     NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_entity_type ON audit_logs (entity_type);
CREATE INDEX idx_audit_logs_entity_id ON audit_logs (entity_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
