<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE class_subjects (
                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id        BIGINT          NOT NULL,
                class_id                BIGINT          NOT NULL,
                section_id              BIGINT          NULL,
                subject_id              BIGINT          NOT NULL,
                subject_name_snapshot   VARCHAR(150)    NOT NULL,
                is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_class_subjects_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_class_subjects_class
                    FOREIGN KEY (class_id) REFERENCES classes (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_class_subjects_section
                    FOREIGN KEY (section_id) REFERENCES sections (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_class_subjects_subject
                    FOREIGN KEY (subject_id) REFERENCES subjects (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("
            CREATE UNIQUE INDEX uk_class_subjects_config
                ON class_subjects (academic_year_id, class_id, (COALESCE(section_id, 0)), subject_id);
        ");

        DB::statement("CREATE INDEX idx_class_subjects_academic_year_id ON class_subjects (academic_year_id);");
        DB::statement("CREATE INDEX idx_class_subjects_class_id ON class_subjects (class_id);");
        DB::statement("CREATE INDEX idx_class_subjects_section_id ON class_subjects (section_id);");
        DB::statement("CREATE INDEX idx_class_subjects_subject_id ON class_subjects (subject_id);");

        DB::statement("
            CREATE TRIGGER trg_class_subjects_updated_at
                BEFORE UPDATE ON class_subjects
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS class_subjects CASCADE;");
    }
};
