<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE student_subject_allocations (
                id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_academic_record_id  BIGINT                  NOT NULL,
                class_subject_id            BIGINT                  NOT NULL,
                allocation_type             subject_category_enum   NOT NULL DEFAULT 'main',
                effective_from              DATE                    NOT NULL,
                effective_to                DATE                    NULL,
                is_active                   BOOLEAN                 NOT NULL DEFAULT TRUE,
                created_at                  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_ssa_record_subject
                    UNIQUE (student_academic_record_id, class_subject_id),

                CONSTRAINT fk_ssa_academic_record
                    FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ssa_class_subject
                    FOREIGN KEY (class_subject_id) REFERENCES class_subjects (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_ssa_student_academic_record_id ON student_subject_allocations (student_academic_record_id);");
        DB::statement("CREATE INDEX idx_ssa_class_subject_id ON student_subject_allocations (class_subject_id);");

        DB::statement("
            CREATE TRIGGER trg_student_subject_allocations_updated_at
                BEFORE UPDATE ON student_subject_allocations
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS student_subject_allocations CASCADE;");
    }
};
