<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE report_configurations (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id    BIGINT              NULL,
                name                VARCHAR(150)        NOT NULL,
                report_type         report_type_enum    NOT NULL,
                configuration_data  JSONB               NULL,
                is_active           BOOLEAN             NOT NULL DEFAULT TRUE,
                created_at          TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_rc_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_rc_academic_year_id ON report_configurations (academic_year_id);");
        DB::statement("CREATE INDEX idx_rc_report_type ON report_configurations (report_type);");

        DB::statement("
            CREATE TRIGGER trg_report_configurations_updated_at
                BEFORE UPDATE ON report_configurations
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS report_configurations CASCADE;");
    }
};
