<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE assessments (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id    BIGINT                  NOT NULL,
                term_id             BIGINT                  NULL,
                assessment_type_id  BIGINT                  NOT NULL,
                name                VARCHAR(150)            NOT NULL,
                assessment_date     DATE                    NULL,
                status              assessment_status_enum  NOT NULL DEFAULT 'active',
                created_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_assessments_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_assessments_term
                    FOREIGN KEY (term_id) REFERENCES terms (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_assessments_type
                    FOREIGN KEY (assessment_type_id) REFERENCES assessment_types (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_assessments_academic_year_id ON assessments (academic_year_id);");
        DB::statement("CREATE INDEX idx_assessments_term_id ON assessments (term_id);");
        DB::statement("CREATE INDEX idx_assessments_assessment_type_id ON assessments (assessment_type_id);");

        DB::statement("
            CREATE TRIGGER trg_assessments_updated_at
                BEFORE UPDATE ON assessments
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS assessments CASCADE;");
    }
};
