<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE sections (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id    BIGINT          NOT NULL,
                class_id            BIGINT          NOT NULL,
                name                VARCHAR(50)     NOT NULL,
                is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_sections_year_class_name
                    UNIQUE (academic_year_id, class_id, name),

                CONSTRAINT fk_sections_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_sections_class
                    FOREIGN KEY (class_id) REFERENCES classes (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_sections_academic_year_id ON sections (academic_year_id);");
        DB::statement("CREATE INDEX idx_sections_class_id ON sections (class_id);");

        DB::statement("
            CREATE TRIGGER trg_sections_updated_at
                BEFORE UPDATE ON sections
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS sections CASCADE;");
    }
};
