<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE calculation_settings (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id    BIGINT                  NOT NULL,
                class_id            BIGINT                  NOT NULL,
                calculation_method  calculation_method_enum NOT NULL,
                created_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_cs_year_class
                    UNIQUE (academic_year_id, class_id),

                CONSTRAINT fk_cs_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_cs_class
                    FOREIGN KEY (class_id) REFERENCES classes (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("
            CREATE TRIGGER trg_calculation_settings_updated_at
                BEFORE UPDATE ON calculation_settings
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS calculation_settings CASCADE;");
    }
};
