<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE attendance (
                id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_academic_record_id  BIGINT          NOT NULL,
                term_id                     BIGINT          NOT NULL,
                days_attended               INTEGER         NOT NULL DEFAULT 0,
                total_working_days          INTEGER         NOT NULL DEFAULT 0,
                entered_by_user_id          BIGINT          NOT NULL,
                updated_by_user_id          BIGINT          NOT NULL,
                created_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_attendance_record_term
                    UNIQUE (student_academic_record_id, term_id),

                CONSTRAINT fk_attendance_academic_record
                    FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_attendance_term
                    FOREIGN KEY (term_id) REFERENCES terms (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_attendance_entered_by
                    FOREIGN KEY (entered_by_user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_attendance_updated_by
                    FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,

                CONSTRAINT chk_attendance_days_not_negative
                    CHECK (days_attended >= 0),
                CONSTRAINT chk_attendance_total_not_negative
                    CHECK (total_working_days >= 0),
                CONSTRAINT chk_attendance_days_within_total
                    CHECK (days_attended <= total_working_days)
            );
        ");

        DB::statement("CREATE INDEX idx_attendance_student_academic_record_id ON attendance (student_academic_record_id);");
        DB::statement("CREATE INDEX idx_attendance_term_id ON attendance (term_id);");

        DB::statement("
            CREATE TRIGGER trg_attendance_updated_at
                BEFORE UPDATE ON attendance
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS attendance CASCADE;");
    }
};
