<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE students (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_name    VARCHAR(200)    NOT NULL,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        DB::statement("CREATE INDEX idx_students_student_name ON students (student_name);");

        DB::statement("
            CREATE TRIGGER trg_students_updated_at
                BEFORE UPDATE ON students
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS students CASCADE;");
    }
};
