<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE school_settings (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                school_name         VARCHAR(200)    NOT NULL,
                school_logo_path    VARCHAR(500)    NULL,
                pass_mark           NUMERIC(6,2)    NOT NULL DEFAULT 0.00,
                created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT chk_ss_pass_mark_non_negative
                    CHECK (pass_mark >= 0)
            );
        ");

        DB::statement("
            CREATE TRIGGER trg_school_settings_updated_at
                BEFORE UPDATE ON school_settings
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS school_settings CASCADE;");
    }
};
