<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE users (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                role_id         BIGINT          NOT NULL,
                username        VARCHAR(100)    NOT NULL,
                password_hash   VARCHAR(255)    NOT NULL,
                display_name    VARCHAR(150)    NOT NULL,
                email           VARCHAR(255)    NULL,
                is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
                last_login_at   TIMESTAMPTZ     NULL,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_users_role
                    FOREIGN KEY (role_id) REFERENCES roles (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE UNIQUE INDEX uk_users_username ON users (LOWER(username));");
        DB::statement("CREATE INDEX idx_users_role_id ON users (role_id);");
        DB::statement("CREATE INDEX idx_users_is_active ON users (is_active);");

        DB::statement("
            CREATE TRIGGER trg_users_updated_at
                BEFORE UPDATE ON users
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS users CASCADE;");
    }
};
