<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE teacher_assignments (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id             BIGINT                          NOT NULL,
                academic_year_id    BIGINT                          NOT NULL,
                class_id            BIGINT                          NOT NULL,
                section_id          BIGINT                          NOT NULL,
                subject_id          BIGINT                          NULL,
                assignment_type     teacher_assignment_type_enum    NOT NULL,
                effective_from      DATE                            NOT NULL,
                effective_to        DATE                            NULL,
                is_active           BOOLEAN                         NOT NULL DEFAULT TRUE,
                created_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_ta_user
                    FOREIGN KEY (user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ta_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ta_class
                    FOREIGN KEY (class_id) REFERENCES classes (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ta_section
                    FOREIGN KEY (section_id) REFERENCES sections (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ta_subject
                    FOREIGN KEY (subject_id) REFERENCES subjects (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,

                CONSTRAINT chk_ta_assignment_subject_consistency
                    CHECK (
                        (assignment_type = 'class_teacher' AND subject_id IS NULL)
                        OR
                        (assignment_type = 'subject_teacher' AND subject_id IS NOT NULL)
                    )
            );
        ");

        DB::statement("CREATE INDEX idx_ta_user_id ON teacher_assignments (user_id);");
        DB::statement("CREATE INDEX idx_ta_academic_year_id ON teacher_assignments (academic_year_id);");
        DB::statement("CREATE INDEX idx_ta_class_id ON teacher_assignments (class_id);");
        DB::statement("CREATE INDEX idx_ta_section_id ON teacher_assignments (section_id);");
        DB::statement("CREATE INDEX idx_ta_subject_id ON teacher_assignments (subject_id);");

        DB::statement("
            CREATE TRIGGER trg_teacher_assignments_updated_at
                BEFORE UPDATE ON teacher_assignments
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS teacher_assignments CASCADE;");
    }
};
