<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE report_assessment_selections (
                id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                report_configuration_id     BIGINT          NOT NULL,
                assessment_id               BIGINT          NOT NULL,
                display_order               INTEGER         NOT NULL,
                is_displayed                BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_ras_config_assessment
                    UNIQUE (report_configuration_id, assessment_id),

                CONSTRAINT fk_ras_report_config
                    FOREIGN KEY (report_configuration_id) REFERENCES report_configurations (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_ras_assessment
                    FOREIGN KEY (assessment_id) REFERENCES assessments (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_ras_report_configuration_id ON report_assessment_selections (report_configuration_id);");
        DB::statement("CREATE INDEX idx_ras_assessment_id ON report_assessment_selections (assessment_id);");
        DB::statement("CREATE INDEX idx_ras_config_display_order ON report_assessment_selections (report_configuration_id, display_order);");

        DB::statement("
            CREATE TRIGGER trg_report_assessment_selections_updated_at
                BEFORE UPDATE ON report_assessment_selections
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS report_assessment_selections CASCADE;");
    }
};
