<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE marks (
                id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_academic_record_id      BIGINT                  NOT NULL,
                student_subject_allocation_id   BIGINT                  NOT NULL,
                assessment_applicability_id     BIGINT                  NOT NULL,
                mark_value                      NUMERIC(6,2)            NULL,
                result_status                   mark_result_status_enum NOT NULL DEFAULT 'blank',
                entered_by_user_id              BIGINT                  NULL,
                updated_by_user_id              BIGINT                  NULL,
                created_at                      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at                      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_marks_allocation_applicability
                    UNIQUE (student_subject_allocation_id, assessment_applicability_id),

                CONSTRAINT fk_marks_academic_record
                    FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_marks_subject_allocation
                    FOREIGN KEY (student_subject_allocation_id) REFERENCES student_subject_allocations (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_marks_assessment_applicability
                    FOREIGN KEY (assessment_applicability_id) REFERENCES assessment_applicability (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_marks_entered_by
                    FOREIGN KEY (entered_by_user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_marks_updated_by
                    FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,

                CONSTRAINT chk_marks_result_consistency
                    CHECK (
                        (result_status = 'numeric' AND mark_value IS NOT NULL AND mark_value >= 0)
                        OR
                        (result_status = 'blank' AND mark_value IS NULL)
                        OR
                        (result_status = 'absent' AND mark_value IS NULL)
                    )
            );
        ");

        DB::statement("CREATE INDEX idx_marks_student_academic_record_id ON marks (student_academic_record_id);");
        DB::statement("CREATE INDEX idx_marks_student_subject_allocation_id ON marks (student_subject_allocation_id);");
        DB::statement("CREATE INDEX idx_marks_assessment_applicability_id ON marks (assessment_applicability_id);");
        DB::statement("CREATE INDEX idx_marks_entered_by_user_id ON marks (entered_by_user_id);");
        DB::statement("CREATE INDEX idx_marks_updated_by_user_id ON marks (updated_by_user_id);");

        DB::statement("
            CREATE TRIGGER trg_marks_updated_at
                BEFORE UPDATE ON marks
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS marks CASCADE;");
    }
};
