<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE student_academic_records (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id          BIGINT                          NOT NULL,
                academic_year_id    BIGINT                          NOT NULL,
                class_id            BIGINT                          NOT NULL,
                section_id          BIGINT                          NOT NULL,
                roll_number         INTEGER                         NOT NULL,
                status              student_placement_status_enum   NOT NULL DEFAULT 'active',
                effective_from      DATE                            NOT NULL,
                effective_to        DATE                            NULL,
                created_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ                     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_sar_year_class_section_roll
                    UNIQUE (academic_year_id, class_id, section_id, roll_number),

                CONSTRAINT fk_sar_student
                    FOREIGN KEY (student_id) REFERENCES students (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_sar_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_sar_class
                    FOREIGN KEY (class_id) REFERENCES classes (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_sar_section
                    FOREIGN KEY (section_id) REFERENCES sections (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_sar_student_id ON student_academic_records (student_id);");
        DB::statement("CREATE INDEX idx_sar_academic_year_id ON student_academic_records (academic_year_id);");
        DB::statement("CREATE INDEX idx_sar_class_id ON student_academic_records (class_id);");
        DB::statement("CREATE INDEX idx_sar_section_id ON student_academic_records (section_id);");

        DB::statement("
            CREATE TRIGGER trg_student_academic_records_updated_at
                BEFORE UPDATE ON student_academic_records
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS student_academic_records CASCADE;");
    }
};
