<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE assessment_types (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(100)    NOT NULL,
                is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        DB::statement("CREATE UNIQUE INDEX uk_assessment_types_name ON assessment_types (LOWER(name));");

        DB::statement("
            CREATE TRIGGER trg_assessment_types_updated_at
                BEFORE UPDATE ON assessment_types
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS assessment_types CASCADE;");
    }
};
