<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE audit_logs (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id         BIGINT          NULL,
                action          VARCHAR(100)    NOT NULL,
                entity_type     VARCHAR(100)    NOT NULL,
                entity_id       BIGINT          NULL,
                before_data     JSONB           NULL,
                after_data      JSONB           NULL,
                description     TEXT            NULL,
                ip_address      VARCHAR(45)     NULL,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_audit_logs_user
                    FOREIGN KEY (user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);");
        DB::statement("CREATE INDEX idx_audit_logs_action ON audit_logs (action);");
        DB::statement("CREATE INDEX idx_audit_logs_entity_type ON audit_logs (entity_type);");
        DB::statement("CREATE INDEX idx_audit_logs_entity_id ON audit_logs (entity_id);");
        DB::statement("CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS audit_logs CASCADE;");
    }
};
