<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE roles (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(50)     NOT NULL,
                description     VARCHAR(255)    NULL,
                is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        DB::statement("CREATE UNIQUE INDEX uk_roles_name ON roles (LOWER(name));");

        DB::statement("
            CREATE TRIGGER trg_roles_updated_at
                BEFORE UPDATE ON roles
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS roles CASCADE;");
    }
};
