<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE generated_reports (
                id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_academic_record_id  BIGINT              NOT NULL,
                report_type                 report_type_enum    NOT NULL,
                term_id                     BIGINT              NULL,
                assessment_id               BIGINT              NULL,
                revision_number             INTEGER             NOT NULL DEFAULT 1,
                file_path                   VARCHAR(500)        NOT NULL,
                generated_by_user_id        BIGINT              NOT NULL,
                generated_at                TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_gr_academic_record
                    FOREIGN KEY (student_academic_record_id) REFERENCES student_academic_records (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_gr_term
                    FOREIGN KEY (term_id) REFERENCES terms (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_gr_assessment
                    FOREIGN KEY (assessment_id) REFERENCES assessments (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_gr_generated_by
                    FOREIGN KEY (generated_by_user_id) REFERENCES users (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("
            CREATE UNIQUE INDEX uk_gr_revision_identity
                ON generated_reports (
                    student_academic_record_id,
                    report_type,
                    (COALESCE(term_id, 0)),
                    (COALESCE(assessment_id, 0)),
                    revision_number
                );
        ");

        DB::statement("CREATE INDEX idx_gr_student_academic_record_id ON generated_reports (student_academic_record_id);");
        DB::statement("CREATE INDEX idx_gr_term_id ON generated_reports (term_id);");
        DB::statement("CREATE INDEX idx_gr_assessment_id ON generated_reports (assessment_id);");
        DB::statement("CREATE INDEX idx_gr_generated_by_user_id ON generated_reports (generated_by_user_id);");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS generated_reports CASCADE;");
    }
};
