<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE academic_years (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(20)                 NOT NULL,
                start_date      DATE                        NULL,
                end_date        DATE                        NULL,
                status          academic_year_status_enum   NOT NULL DEFAULT 'open',
                is_current      BOOLEAN                     NOT NULL DEFAULT FALSE,
                created_at      TIMESTAMPTZ                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ                 NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        DB::statement("CREATE UNIQUE INDEX uk_academic_years_name ON academic_years (LOWER(name));");

        DB::statement("
            CREATE TRIGGER trg_academic_years_updated_at
                BEFORE UPDATE ON academic_years
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS academic_years CASCADE;");
    }
};
