<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE assessment_applicability (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assessment_id       BIGINT          NOT NULL,
                class_subject_id    BIGINT          NOT NULL,
                maximum_marks       NUMERIC(6,2)    NOT NULL,
                is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_aa_assessment_class_subject
                    UNIQUE (assessment_id, class_subject_id),

                CONSTRAINT fk_aa_assessment
                    FOREIGN KEY (assessment_id) REFERENCES assessments (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,
                CONSTRAINT fk_aa_class_subject
                    FOREIGN KEY (class_subject_id) REFERENCES class_subjects (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT,

                CONSTRAINT chk_aa_max_marks_positive
                    CHECK (maximum_marks > 0)
            );
        ");

        DB::statement("CREATE INDEX idx_aa_assessment_id ON assessment_applicability (assessment_id);");
        DB::statement("CREATE INDEX idx_aa_class_subject_id ON assessment_applicability (class_subject_id);");

        DB::statement("
            CREATE TRIGGER trg_assessment_applicability_updated_at
                BEFORE UPDATE ON assessment_applicability
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS assessment_applicability CASCADE;");
    }
};
