<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE subjects (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(150)            NOT NULL,
                code            VARCHAR(50)             NULL,
                category        subject_category_enum   NOT NULL DEFAULT 'main',
                is_active       BOOLEAN                 NOT NULL DEFAULT TRUE,
                created_at      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        DB::statement("CREATE UNIQUE INDEX uk_subjects_name ON subjects (LOWER(name));");

        DB::statement("
            CREATE TRIGGER trg_subjects_updated_at
                BEFORE UPDATE ON subjects
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS subjects CASCADE;");
    }
};
