<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            CREATE TABLE terms (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academic_year_id    BIGINT          NOT NULL,
                name                VARCHAR(100)    NOT NULL,
                sequence_no         INTEGER         NOT NULL,
                is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
                created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT uk_terms_year_seq
                    UNIQUE (academic_year_id, sequence_no),
                CONSTRAINT uk_terms_year_name
                    UNIQUE (academic_year_id, name),

                CONSTRAINT fk_terms_academic_year
                    FOREIGN KEY (academic_year_id) REFERENCES academic_years (id)
                    ON DELETE RESTRICT ON UPDATE RESTRICT
            );
        ");

        DB::statement("
            CREATE TRIGGER trg_terms_updated_at
                BEFORE UPDATE ON terms
                FOR EACH ROW
                EXECUTE FUNCTION trigger_set_updated_at();
        ");
    }

    public function down(): void
    {
        DB::statement("DROP TABLE IF EXISTS terms CASCADE;");
    }
};
